package Menu;

import VCFprocesses.VCFResults;
import javax.swing.ImageIcon;

/**
 * Classe responsável por mostrar alguns resultados retirados do arquivo VCF.
 * @author eliseumedeiros
 */
public class JFrame_Informations extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Informations
     * @param newresultados
     */
    public JFrame_Informations( VCFResults newresultados) {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/icon_gene.png").getPath());
        setIconImage(icon.getImage());
        this.resultados = newresultados;
        preencerTabelas();
    }
    public void preencerTabelas(){
        jTableGeralResults.setModel(resultados.getTabelaGeralResults());
        jTableGeralResults.setModel(new javax.swing.table.DefaultTableModel(
                    resultados.getTabelaGeralResults().getMatrizTable(),
                    resultados.getTabelaGeralResults().getColunas()
        ));
        
        jTableGeralResults.setModel(resultados.getTabelaCHROMResults());
        jTableCHOMResults.setModel(new javax.swing.table.DefaultTableModel(
                    resultados.getTabelaCHROMResults().getMatrizTable(),
                    resultados.getTabelaCHROMResults().getColunas()
        ));
        
        jTableGeralResults.setModel(resultados.getTabelaQUALResults());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabIcon = new javax.swing.JLabel();
        jTituloTable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableGeralResults = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCHOMResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 200, 167)));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 764));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 645));

        jLabIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_gene.png"))); // NOI18N

        jTituloTable.setBackground(new java.awt.Color(255, 255, 255));
        jTituloTable.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTituloTable.setForeground(new java.awt.Color(47, 77, 77));
        jTituloTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTituloTable.setText("VCF - Processes");
        jTituloTable.setAutoscrolls(true);
        jTituloTable.setMaximumSize(new java.awt.Dimension(200, 32));
        jTituloTable.setMinimumSize(new java.awt.Dimension(200, 32));
        jTituloTable.setPreferredSize(new java.awt.Dimension(215, 40));
        jTituloTable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 77, 77));
        jLabel1.setText("More Informations");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Quality:");

        jTableGeralResults.setForeground(new java.awt.Color(61, 2, 2));
        jTableGeralResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "result", "value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGeralResults.setGridColor(new java.awt.Color(85, 200, 167));
        jTableGeralResults.setSelectionBackground(new java.awt.Color(4, 204, 204));
        jScrollPane4.setViewportView(jTableGeralResults);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Chromo:");

        jTableCHOMResults.setForeground(new java.awt.Color(61, 2, 2));
        jTableCHOMResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CHROM", "Occurrence"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCHOMResults.setGridColor(new java.awt.Color(85, 200, 167));
        jTableCHOMResults.setSelectionBackground(new java.awt.Color(4, 204, 204));
        jScrollPane3.setViewportView(jTableCHOMResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTituloTable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabIcon)
                    .addComponent(jTituloTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    VCFResults resultados;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCHOMResults;
    private javax.swing.JTable jTableGeralResults;
    private javax.swing.JLabel jTituloTable;
    // End of variables declaration//GEN-END:variables
}
